### ISSUE TITLE
Is there no documentation for this???

### ISSUE THREAD

**Issue by scott-taylor-fruition** [headwinds/daterangepicker#1]
Kind of hard to implement when there is no documentation, or any kind of clarity in the demo.  How is the element initially instantiated?

**Comment by headwinds** [comment]
Beyond the readme which outlines the purpose, I see I didn't properly explain how to use it. Right now, you basically need to download and play with it to see how it works. There's not a ton of code; basically 2 scripts: the one that draws the calendars and one that controls selecting the dates and handles some validation between date ranges.

There is a init function (line 163) in DateRangeViewController which is called as soon as the script loads. You will see init() fire near the end of this file. Init initializes everything. 

This was written well before components and es6 classes so there is no one element. The controller talks many elements on the provided html page. It has all the raw pieces to be ported into a modern component though. 

If I had to do date range comparison today, I'd leverage the moment date math from this project and build a React based date range picker. While I definitely agree that its challenging to use in its current state, there may be some gold in here worth mining.

**Comment by headwinds** [comment]
I've updated the readme and gave proper warning about this being a challenging repo to implement without learning from the source.
